name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Build check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn
      - run: yarn build
