# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  github-pages:

    name: Deploy to github pages

    if: github.repository_owner == 'coajs'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn

      - name: Release to GitHub Pages
        env:
          GIT_PASS: ${{ secrets.AEX_BOT_TOKEN }}
        run: |
          git config --global user.email "spryti@163.com"
          git config --global user.name "AexBot"
          yarn deploy
