# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - main

jobs:

  github-pages:

    name: Deploy to github pages

    if: github.repository_owner == 'coajs'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - name: Deploy to github pages
        run: |
          git config --global user.email "spryti@163.com"
          git config --global user.name "AexBot"
          git remote set-url origin https://aex-bot:${{ secrets.AEX_BOT_TOKEN }}@github.com/coajs/coa-website.git
          yarn deploy
