name: Release

on:
  push:
    branches:
      - release

jobs:
  to-github-pages:
    name: Deploy to github pages

    if: ${{ github.repository_owner == 'coajs' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn docs:build

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: src/.vitepress/dist
